[package]
name = "foreverhash"
version = "0.1.0"
edition = "2024"

[dependencies]
crc32fast.workspace = true
rkyv.workspace = true
sha2 = "0.10"
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
