[package]
name = "foreverdb"
version = "0.1.0"
edition = "2024"

[dependencies]
crc32fast.workspace = true
rkyv.workspace = true
thiserror.workspace = true

foreverhash = { path = "../foreverhash" }

[dev-dependencies]
tempfile.workspace = true